### PR TITLE
Add 'Bootstrap modal  option'.

### PR DESCRIPTION
**Pull request by kntmrkm**
Hi.

I want to set `backdrop` option.

Which option can prevent hide modal by click window.
When modal hidden by click, `onCancel` event does not work.

I want a event option which certainly do event action.

Could you check my PR?

thanks.

### CODE REVIEW

**Comment by kntmrkm** [comment]
ping

**Comment by vjt** [comment]
pong, sorry for the delay, will review

**Comment by vjt** [comment]
Thanks @kntmrkm - I've built on your work and added support for all currently supported bootstrap options.

This means that now you can either `setDefaults` with the options you want, or pass the `backdrop: false` option when invoking the modal via JS, or use `data-backdrop="false"` on your HTML element.

Kind regards,

~Marcello

**Comment by kntmrkm** [comment]
Oh great!
thanks Marcello!

**Pull request merged**
