### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by dapicester**
I added a minimal `bower.json` so that one can include this in other projects, also non-Rails projects (I am currently using it in a Django project where I manage my front-end packages with [Bower](https://bower.io/)).

### CODE REVIEW

**Comment by vjt** [comment]
Thanks! Shouldn't we also add a bootstrap dependency? Then, out of curiosity, are you using `jquery-ujs` in your Django project?

Thanks again

**Comment by dapicester** [comment]
Yes, I am using `jquery-ujs` (I miss Rails...)
You're also right about bootstrap dependency, I'll try to put that in and test. If it works I'll submit another PR.

However, even the Bower website suggests to switch to [yarn](https://yarnpkg.com/), which is supported in [Rails 5.1](http://guides.rubyonrails.org/5_1_release_notes.html#yarn-support).
If I will ever make the switch I'll try to add a simple `package.json` too.

Thanks for merging!

**Comment by dapicester** [comment]
I added dependency to bootstrap and fixed the versions.

**Comment by vjt** [comment]
Thanks!

**Pull request merged**
